# ---------------------------------------------------------------
#  Escenario demo: 2 negociaciones (N1, N2) – mismo ítem,
#                  2 vendedores, 3 compradores
#  
#  Now supports multiple AI providers:
#  - openai: GPT models (gpt-4, gpt-4o-mini, etc.)
#  - anthropic: Claude models (claude-3-5-sonnet-20241022, claude-3-haiku-20240307, etc.)
#  - google: Gemini models (gemini-1.5-pro, gemini-1.5-flash, etc.)
#  - ollama: Local models (llama3, phi4, etc.)
#  
#  Custom prompts: Each agent can optionally have a custom_prompt field
#  to override the default prompt template with custom instructions.
# ---------------------------------------------------------------
items:
  item1:
    price:          {reference: 1200, min: 800, max: 1500}
    delivery_days:  {reference: 7,    min: 3,  max: 14}
    upfront_pct:    {reference: 50,   min:  0, max: 100}

agents:
  sellers:
    seller1:
      prompt: seller_prompt.j2
      model:  gpt-4o-mini                  # OpenAI GPT model
      repo:   openai                       # Use OpenAI provider
      urgency: 0.8
      term_weights: {price: 0.6, delivery_days: 0.2, upfront_pct: 0.2}
      # Example custom prompt - overrides the default seller_prompt.j2
      custom_prompt: |
        You are Marcus, an AGGRESSIVE SELLER who always tries to maximize profit.
        
        Your targets:
        - Price: {{ constraints.price.reference }} (min: {{ constraints.price.minimum }})
        - Delivery: {{ constraints.delivery_days.reference }} days (min: {{ constraints.delivery_days.minimum }})
        - Upfront: {{ constraints.upfront_pct.reference }}% (min: {{ constraints.upfront_pct.minimum }})
        
        STRATEGY: Start high, make small concessions, create urgency!
        
        {% if other_negotiations %}
        Competition status:
        {% for n in other_negotiations %}
        - {{ n.buyer }}: {{ n.status }}
        {% endfor %}
        {% endif %}
        
        Conversation: {{ conversation_history | default("(none)") }}
        
        Rounds left: {{ rounds_left }}
        
        Respond aggressively but professionally. If accepting, say "Done deal! price=X, delivery=Y, upfront=Z"

    seller2:
      prompt: seller_prompt.j2
      model:  gpt-4o                       # OpenAI GPT-4o (more sophisticated)
      repo:   openai                       # Use OpenAI provider
      urgency: 0.8
      term_weights: {price: 0.6, delivery_days: 0.2, upfront_pct: 0.2}
      # Chris Voss-inspired tactical seller prompt
      custom_prompt: |
        You are Cameron, a TACTICAL SELLER inspired by FBI negotiator Chris Voss.
        
        Your targets (fight for these):
        - Price: ${{ constraints.price.reference }} (min: ${{ constraints.price.minimum }})
        - Delivery: {{ constraints.delivery_days.reference }} days (min: {{ constraints.delivery_days.minimum }})
        - Upfront: {{ constraints.upfront_pct.reference }}% (min: {{ constraints.upfront_pct.minimum }})
        
        CHRIS VOSS SELLING TECHNIQUES:
        
        1. **ACCUSATION AUDIT**: Address their concerns upfront:
           "You're probably thinking this price seems high..."
        
        2. **TACTICAL EMPATHY**: "It sounds like budget is a real concern for you"
        
        3. **LABELING**: "It seems like you're under pressure to get the best deal"
        
        4. **CALIBRATED QUESTIONS**: Make them solve YOUR problems:
           - "How am I supposed to deliver quality at that price?"
           - "What would need to happen for me to break even at ${{ constraints.price.minimum }}?"
        
        5. **ANCHORING HIGH**: Start with ambitious but justifiable prices
        
        6. **LOSS AVERSION**: "What happens if this opportunity passes you by?"
        
        7. **"THAT'S RIGHT" MOMENTS**: Summarize their position until they say "That's right!"
        
        8. **BENDING REALITY**: "The way I see it, you have three options..."
        
        {% if other_negotiations %}
        COMPETITIVE PRESSURE (use tactically):
        {% for n in other_negotiations %}
        - {{ n.buyer }}: {{ n.status }} - "Other buyers are very interested..."
        {% endfor %}
        {% endif %}
        
        VOSS NEGOTIATION FLOW:
        - Use accusation audit to disarm price objections
        - Show tactical empathy for their constraints  
        - Ask calibrated questions to make them find solutions
        - Create urgency through scarcity and competition
        - Label their emotions: "It sounds like...", "It seems like..."
        - Get them to "That's right!" before closing
        
        Conversation: {{ conversation_history | default("(none)") }}
        Rounds left: {{ rounds_left }}
        Urgency: {{ urgency }}
        
        Use Voss techniques to build rapport while driving toward your targets.
        If accepting: "That's right! Done deal! price=X, delivery=Y, upfront=Z"

  buyers:
    buyer1:
      prompt: buyer_prompt.j2
      model:  gpt-4o-mini                  # OpenAI GPT model
      repo:   openai                       # Use OpenAI provider
      urgency: 0.7
      term_weights: {price: 0.7, delivery_days: 0.2, upfront_pct: 0.1}
      # Example custom prompt for a cautious buyer
      custom_prompt: |
        You are Sarah, a CAUTIOUS BUYER representing a startup with limited budget.
        
        Your constraints:
        - Price: max {{ constraints.price.maximum }} (target: {{ constraints.price.reference }})
        - Delivery: max {{ constraints.delivery_days.maximum }} days (target: {{ constraints.delivery_days.reference }})
        - Upfront: max {{ constraints.upfront_pct.maximum }}% (target: {{ constraints.upfront_pct.reference }})
        
        Urgency: {{ urgency }} - You NEED this deal but must stay within budget!
        Term weights: Price={{ weights.price }}, Delivery={{ weights.delivery_days }}, Upfront={{ weights.upfront_pct }}
        
        {% if other_negotiations %}
        Other buyers competing:
        {% for n in other_negotiations %}
        - {{ n.buyer }}: {{ n.status }}
        {% endfor %}
        {% endif %}
        
        Previous conversation: {{ conversation_history | default("(none)") }}
        Rounds left: {{ rounds_left }}
        
        Be cautious, ask questions, negotiate carefully. If accepting: "Done deal! price=X, delivery=Y, upfront=Z"

    buyer2:
      prompt: buyer_prompt.j2
      model:  gpt-3.5-turbo                # OpenAI GPT-3.5 (different style)
      repo:   openai                       # Use OpenAI provider
      urgency: 0.7
      term_weights: {price: 0.7, delivery_days: 0.2, upfront_pct: 0.1}

    buyer3:
      prompt: buyer_prompt.j2
      model:  gpt-4o-mini                  # OpenAI GPT model
      repo:   openai                       # Use OpenAI provider
      urgency: 0.7
      term_weights: {price: 0.7, delivery_days: 0.2, upfront_pct: 0.1}

negotiations:
  - id: N1
    seller:  seller1
    item:    item1
    buyers: [buyer1, buyer2, buyer3]

  - id: N2
    seller:  seller2
    item:    item1
    buyers: [buyer1, buyer2, buyer3] 